public class Wrappersplitmsg {
    public string Phone{set;get;}
    public string TextMessage{set;get;}
    public string LastName{set;get;}
     public string Name{set;get;}
    public string Email{set;get;}
     
     public string Brand{set;get;}
     public string website{set;get;}
       public string Company{set;get;}
     public string Address{set;get;}
        public string City{set;get;}
       public string State{set;get;}
     public string Zip{set;get;}
      public string Comments{set;get;}

}